 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/allocataire_cnavs", type: :request do
  # AllocataireCnav. As you add validations to AllocataireCnav, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AllocataireCnav.create! valid_attributes
      get allocataire_cnavs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      allocataire_cnav = AllocataireCnav.create! valid_attributes
      get allocataire_cnav_url(allocataire_cnav)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_allocataire_cnav_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      allocataire_cnav = AllocataireCnav.create! valid_attributes
      get edit_allocataire_cnav_url(allocataire_cnav)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AllocataireCnav" do
        expect {
          post allocataire_cnavs_url, params: { allocataire_cnav: valid_attributes }
        }.to change(AllocataireCnav, :count).by(1)
      end

      it "redirects to the created allocataire_cnav" do
        post allocataire_cnavs_url, params: { allocataire_cnav: valid_attributes }
        expect(response).to redirect_to(allocataire_cnav_url(AllocataireCnav.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AllocataireCnav" do
        expect {
          post allocataire_cnavs_url, params: { allocataire_cnav: invalid_attributes }
        }.to change(AllocataireCnav, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post allocataire_cnavs_url, params: { allocataire_cnav: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested allocataire_cnav" do
        allocataire_cnav = AllocataireCnav.create! valid_attributes
        patch allocataire_cnav_url(allocataire_cnav), params: { allocataire_cnav: new_attributes }
        allocataire_cnav.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the allocataire_cnav" do
        allocataire_cnav = AllocataireCnav.create! valid_attributes
        patch allocataire_cnav_url(allocataire_cnav), params: { allocataire_cnav: new_attributes }
        allocataire_cnav.reload
        expect(response).to redirect_to(allocataire_cnav_url(allocataire_cnav))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        allocataire_cnav = AllocataireCnav.create! valid_attributes
        patch allocataire_cnav_url(allocataire_cnav), params: { allocataire_cnav: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested allocataire_cnav" do
      allocataire_cnav = AllocataireCnav.create! valid_attributes
      expect {
        delete allocataire_cnav_url(allocataire_cnav)
      }.to change(AllocataireCnav, :count).by(-1)
    end

    it "redirects to the allocataire_cnavs list" do
      allocataire_cnav = AllocataireCnav.create! valid_attributes
      delete allocataire_cnav_url(allocataire_cnav)
      expect(response).to redirect_to(allocataire_cnavs_url)
    end
  end
end
