 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/at_carnets", type: :request do
  # AtCarnet. As you add validations to AtCarnet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AtCarnet.create! valid_attributes
      get at_carnets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      at_carnet = AtCarnet.create! valid_attributes
      get at_carnet_url(at_carnet)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_at_carnet_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      at_carnet = AtCarnet.create! valid_attributes
      get edit_at_carnet_url(at_carnet)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AtCarnet" do
        expect {
          post at_carnets_url, params: { at_carnet: valid_attributes }
        }.to change(AtCarnet, :count).by(1)
      end

      it "redirects to the created at_carnet" do
        post at_carnets_url, params: { at_carnet: valid_attributes }
        expect(response).to redirect_to(at_carnet_url(AtCarnet.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AtCarnet" do
        expect {
          post at_carnets_url, params: { at_carnet: invalid_attributes }
        }.to change(AtCarnet, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post at_carnets_url, params: { at_carnet: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested at_carnet" do
        at_carnet = AtCarnet.create! valid_attributes
        patch at_carnet_url(at_carnet), params: { at_carnet: new_attributes }
        at_carnet.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the at_carnet" do
        at_carnet = AtCarnet.create! valid_attributes
        patch at_carnet_url(at_carnet), params: { at_carnet: new_attributes }
        at_carnet.reload
        expect(response).to redirect_to(at_carnet_url(at_carnet))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        at_carnet = AtCarnet.create! valid_attributes
        patch at_carnet_url(at_carnet), params: { at_carnet: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested at_carnet" do
      at_carnet = AtCarnet.create! valid_attributes
      expect {
        delete at_carnet_url(at_carnet)
      }.to change(AtCarnet, :count).by(-1)
    end

    it "redirects to the at_carnets list" do
      at_carnet = AtCarnet.create! valid_attributes
      delete at_carnet_url(at_carnet)
      expect(response).to redirect_to(at_carnets_url)
    end
  end
end
