 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/at_guerisons", type: :request do
  # AtGuerison. As you add validations to AtGuerison, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AtGuerison.create! valid_attributes
      get at_guerisons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      at_guerison = AtGuerison.create! valid_attributes
      get at_guerison_url(at_guerison)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_at_guerison_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      at_guerison = AtGuerison.create! valid_attributes
      get edit_at_guerison_url(at_guerison)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AtGuerison" do
        expect {
          post at_guerisons_url, params: { at_guerison: valid_attributes }
        }.to change(AtGuerison, :count).by(1)
      end

      it "redirects to the created at_guerison" do
        post at_guerisons_url, params: { at_guerison: valid_attributes }
        expect(response).to redirect_to(at_guerison_url(AtGuerison.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AtGuerison" do
        expect {
          post at_guerisons_url, params: { at_guerison: invalid_attributes }
        }.to change(AtGuerison, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post at_guerisons_url, params: { at_guerison: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested at_guerison" do
        at_guerison = AtGuerison.create! valid_attributes
        patch at_guerison_url(at_guerison), params: { at_guerison: new_attributes }
        at_guerison.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the at_guerison" do
        at_guerison = AtGuerison.create! valid_attributes
        patch at_guerison_url(at_guerison), params: { at_guerison: new_attributes }
        at_guerison.reload
        expect(response).to redirect_to(at_guerison_url(at_guerison))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        at_guerison = AtGuerison.create! valid_attributes
        patch at_guerison_url(at_guerison), params: { at_guerison: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested at_guerison" do
      at_guerison = AtGuerison.create! valid_attributes
      expect {
        delete at_guerison_url(at_guerison)
      }.to change(AtGuerison, :count).by(-1)
    end

    it "redirects to the at_guerisons list" do
      at_guerison = AtGuerison.create! valid_attributes
      delete at_guerison_url(at_guerison)
      expect(response).to redirect_to(at_guerisons_url)
    end
  end
end
