 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/base_reversion_salaries", type: :request do
  # BaseReversionSalary. As you add validations to BaseReversionSalary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BaseReversionSalary.create! valid_attributes
      get base_reversion_salaries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      base_reversion_salary = BaseReversionSalary.create! valid_attributes
      get base_reversion_salary_url(base_reversion_salary)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_base_reversion_salary_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      base_reversion_salary = BaseReversionSalary.create! valid_attributes
      get edit_base_reversion_salary_url(base_reversion_salary)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BaseReversionSalary" do
        expect {
          post base_reversion_salaries_url, params: { base_reversion_salary: valid_attributes }
        }.to change(BaseReversionSalary, :count).by(1)
      end

      it "redirects to the created base_reversion_salary" do
        post base_reversion_salaries_url, params: { base_reversion_salary: valid_attributes }
        expect(response).to redirect_to(base_reversion_salary_url(BaseReversionSalary.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BaseReversionSalary" do
        expect {
          post base_reversion_salaries_url, params: { base_reversion_salary: invalid_attributes }
        }.to change(BaseReversionSalary, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post base_reversion_salaries_url, params: { base_reversion_salary: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested base_reversion_salary" do
        base_reversion_salary = BaseReversionSalary.create! valid_attributes
        patch base_reversion_salary_url(base_reversion_salary), params: { base_reversion_salary: new_attributes }
        base_reversion_salary.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the base_reversion_salary" do
        base_reversion_salary = BaseReversionSalary.create! valid_attributes
        patch base_reversion_salary_url(base_reversion_salary), params: { base_reversion_salary: new_attributes }
        base_reversion_salary.reload
        expect(response).to redirect_to(base_reversion_salary_url(base_reversion_salary))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        base_reversion_salary = BaseReversionSalary.create! valid_attributes
        patch base_reversion_salary_url(base_reversion_salary), params: { base_reversion_salary: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested base_reversion_salary" do
      base_reversion_salary = BaseReversionSalary.create! valid_attributes
      expect {
        delete base_reversion_salary_url(base_reversion_salary)
      }.to change(BaseReversionSalary, :count).by(-1)
    end

    it "redirects to the base_reversion_salaries list" do
      base_reversion_salary = BaseReversionSalary.create! valid_attributes
      delete base_reversion_salary_url(base_reversion_salary)
      expect(response).to redirect_to(base_reversion_salaries_url)
    end
  end
end
