 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prestation_ext_frances", type: :request do
  # PrestationExtFrance. As you add validations to PrestationExtFrance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CfsReversionVeuve.create! valid_attributes
      get prestation_ext_frances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prestation_ext_france = CfsReversionVeuve.create! valid_attributes
      get prestation_ext_france_url(prestation_ext_france)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prestation_ext_france_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      prestation_ext_france = CfsReversionVeuve.create! valid_attributes
      get edit_prestation_ext_france_url(prestation_ext_france)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PrestationExtFrance" do
        expect {
          post prestation_ext_frances_url, params: { prestation_ext_france: valid_attributes }
        }.to change(CfsReversionVeuve, :count).by(1)
      end

      it "redirects to the created prestation_ext_france" do
        post prestation_ext_frances_url, params: { prestation_ext_france: valid_attributes }
        expect(response).to redirect_to(prestation_ext_france_url(CfsReversionVeuve.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PrestationExtFrance" do
        expect {
          post prestation_ext_frances_url, params: { prestation_ext_france: invalid_attributes }
        }.to change(CfsReversionVeuve, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post prestation_ext_frances_url, params: { prestation_ext_france: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prestation_ext_france" do
        prestation_ext_france = CfsReversionVeuve.create! valid_attributes
        patch prestation_ext_france_url(prestation_ext_france), params: { prestation_ext_france: new_attributes }
        prestation_ext_france.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prestation_ext_france" do
        prestation_ext_france = CfsReversionVeuve.create! valid_attributes
        patch prestation_ext_france_url(prestation_ext_france), params: { prestation_ext_france: new_attributes }
        prestation_ext_france.reload
        expect(response).to redirect_to(prestation_ext_france_url(prestation_ext_france))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        prestation_ext_france = CfsReversionVeuve.create! valid_attributes
        patch prestation_ext_france_url(prestation_ext_france), params: { prestation_ext_france: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prestation_ext_france" do
      prestation_ext_france = CfsReversionVeuve.create! valid_attributes
      expect {
        delete prestation_ext_france_url(prestation_ext_france)
      }.to change(CfsReversionVeuve, :count).by(-1)
    end

    it "redirects to the prestation_ext_frances list" do
      prestation_ext_france = CfsReversionVeuve.create! valid_attributes
      delete prestation_ext_france_url(prestation_ext_france)
      expect(response).to redirect_to(prestation_ext_frances_url)
    end
  end
end
