 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cips", type: :request do
  # Cip. As you add validations to Cip, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cip.create! valid_attributes
      get cips_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cip = Cip.create! valid_attributes
      get cip_url(cip)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cip_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cip = Cip.create! valid_attributes
      get edit_cip_url(cip)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cip" do
        expect {
          post cips_url, params: { cip: valid_attributes }
        }.to change(Cip, :count).by(1)
      end

      it "redirects to the created cip" do
        post cips_url, params: { cip: valid_attributes }
        expect(response).to redirect_to(cip_url(Cip.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cip" do
        expect {
          post cips_url, params: { cip: invalid_attributes }
        }.to change(Cip, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cips_url, params: { cip: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cip" do
        cip = Cip.create! valid_attributes
        patch cip_url(cip), params: { cip: new_attributes }
        cip.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cip" do
        cip = Cip.create! valid_attributes
        patch cip_url(cip), params: { cip: new_attributes }
        cip.reload
        expect(response).to redirect_to(cip_url(cip))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cip = Cip.create! valid_attributes
        patch cip_url(cip), params: { cip: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cip" do
      cip = Cip.create! valid_attributes
      expect {
        delete cip_url(cip)
      }.to change(Cip, :count).by(-1)
    end

    it "redirects to the cips list" do
      cip = Cip.create! valid_attributes
      delete cip_url(cip)
      expect(response).to redirect_to(cips_url)
    end
  end
end
