 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/declaration_divorce_ou_deces_conjoints", type: :request do
  # DeclarationDivorceOuDecesConjoint. As you add validations to DeclarationDivorceOuDecesConjoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DeclarationDivorceOuDecesConjoint.create! valid_attributes
      get declaration_divorce_ou_deces_conjoints_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      declaration_divorce_ou_deces_conjoint = DeclarationDivorceOuDecesConjoint.create! valid_attributes
      get declaration_divorce_ou_deces_conjoint_url(declaration_divorce_ou_deces_conjoint)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_declaration_divorce_ou_deces_conjoint_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      declaration_divorce_ou_deces_conjoint = DeclarationDivorceOuDecesConjoint.create! valid_attributes
      get edit_declaration_divorce_ou_deces_conjoint_url(declaration_divorce_ou_deces_conjoint)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DeclarationDivorceOuDecesConjoint" do
        expect {
          post declaration_divorce_ou_deces_conjoints_url, params: { declaration_divorce_ou_deces_conjoint: valid_attributes }
        }.to change(DeclarationDivorceOuDecesConjoint, :count).by(1)
      end

      it "redirects to the created declaration_divorce_ou_deces_conjoint" do
        post declaration_divorce_ou_deces_conjoints_url, params: { declaration_divorce_ou_deces_conjoint: valid_attributes }
        expect(response).to redirect_to(declaration_divorce_ou_deces_conjoint_url(DeclarationDivorceOuDecesConjoint.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DeclarationDivorceOuDecesConjoint" do
        expect {
          post declaration_divorce_ou_deces_conjoints_url, params: { declaration_divorce_ou_deces_conjoint: invalid_attributes }
        }.to change(DeclarationDivorceOuDecesConjoint, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post declaration_divorce_ou_deces_conjoints_url, params: { declaration_divorce_ou_deces_conjoint: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested declaration_divorce_ou_deces_conjoint" do
        declaration_divorce_ou_deces_conjoint = DeclarationDivorceOuDecesConjoint.create! valid_attributes
        patch declaration_divorce_ou_deces_conjoint_url(declaration_divorce_ou_deces_conjoint), params: { declaration_divorce_ou_deces_conjoint: new_attributes }
        declaration_divorce_ou_deces_conjoint.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the declaration_divorce_ou_deces_conjoint" do
        declaration_divorce_ou_deces_conjoint = DeclarationDivorceOuDecesConjoint.create! valid_attributes
        patch declaration_divorce_ou_deces_conjoint_url(declaration_divorce_ou_deces_conjoint), params: { declaration_divorce_ou_deces_conjoint: new_attributes }
        declaration_divorce_ou_deces_conjoint.reload
        expect(response).to redirect_to(declaration_divorce_ou_deces_conjoint_url(declaration_divorce_ou_deces_conjoint))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        declaration_divorce_ou_deces_conjoint = DeclarationDivorceOuDecesConjoint.create! valid_attributes
        patch declaration_divorce_ou_deces_conjoint_url(declaration_divorce_ou_deces_conjoint), params: { declaration_divorce_ou_deces_conjoint: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested declaration_divorce_ou_deces_conjoint" do
      declaration_divorce_ou_deces_conjoint = DeclarationDivorceOuDecesConjoint.create! valid_attributes
      expect {
        delete declaration_divorce_ou_deces_conjoint_url(declaration_divorce_ou_deces_conjoint)
      }.to change(DeclarationDivorceOuDecesConjoint, :count).by(-1)
    end

    it "redirects to the declaration_divorce_ou_deces_conjoints list" do
      declaration_divorce_ou_deces_conjoint = DeclarationDivorceOuDecesConjoint.create! valid_attributes
      delete declaration_divorce_ou_deces_conjoint_url(declaration_divorce_ou_deces_conjoint)
      expect(response).to redirect_to(declaration_divorce_ou_deces_conjoints_url)
    end
  end
end
