 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/demande_remboursement_cotisations", type: :request do
  # DemandeRemboursementCotisation. As you add validations to DemandeRemboursementCotisation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DemandeRemboursementCotisation.create! valid_attributes
      get demande_remboursement_cotisations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      demande_remboursement_cotisation = DemandeRemboursementCotisation.create! valid_attributes
      get demande_remboursement_cotisation_url(demande_remboursement_cotisation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_demande_remboursement_cotisation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      demande_remboursement_cotisation = DemandeRemboursementCotisation.create! valid_attributes
      get edit_demande_remboursement_cotisation_url(demande_remboursement_cotisation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DemandeRemboursementCotisation" do
        expect {
          post demande_remboursement_cotisations_url, params: { demande_remboursement_cotisation: valid_attributes }
        }.to change(DemandeRemboursementCotisation, :count).by(1)
      end

      it "redirects to the created demande_remboursement_cotisation" do
        post demande_remboursement_cotisations_url, params: { demande_remboursement_cotisation: valid_attributes }
        expect(response).to redirect_to(demande_remboursement_cotisation_url(DemandeRemboursementCotisation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DemandeRemboursementCotisation" do
        expect {
          post demande_remboursement_cotisations_url, params: { demande_remboursement_cotisation: invalid_attributes }
        }.to change(DemandeRemboursementCotisation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post demande_remboursement_cotisations_url, params: { demande_remboursement_cotisation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested demande_remboursement_cotisation" do
        demande_remboursement_cotisation = DemandeRemboursementCotisation.create! valid_attributes
        patch demande_remboursement_cotisation_url(demande_remboursement_cotisation), params: { demande_remboursement_cotisation: new_attributes }
        demande_remboursement_cotisation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the demande_remboursement_cotisation" do
        demande_remboursement_cotisation = DemandeRemboursementCotisation.create! valid_attributes
        patch demande_remboursement_cotisation_url(demande_remboursement_cotisation), params: { demande_remboursement_cotisation: new_attributes }
        demande_remboursement_cotisation.reload
        expect(response).to redirect_to(demande_remboursement_cotisation_url(demande_remboursement_cotisation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        demande_remboursement_cotisation = DemandeRemboursementCotisation.create! valid_attributes
        patch demande_remboursement_cotisation_url(demande_remboursement_cotisation), params: { demande_remboursement_cotisation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested demande_remboursement_cotisation" do
      demande_remboursement_cotisation = DemandeRemboursementCotisation.create! valid_attributes
      expect {
        delete demande_remboursement_cotisation_url(demande_remboursement_cotisation)
      }.to change(DemandeRemboursementCotisation, :count).by(-1)
    end

    it "redirects to the demande_remboursement_cotisations list" do
      demande_remboursement_cotisation = DemandeRemboursementCotisation.create! valid_attributes
      delete demande_remboursement_cotisation_url(demande_remboursement_cotisation)
      expect(response).to redirect_to(demande_remboursement_cotisations_url)
    end
  end
end
