 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dossier_cnavs", type: :request do
  # DossierCnav. As you add validations to DossierCnav, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DossierCnav.create! valid_attributes
      get dossier_cnavs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dossier_cnav = DossierCnav.create! valid_attributes
      get dossier_cnav_url(dossier_cnav)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dossier_cnav_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dossier_cnav = DossierCnav.create! valid_attributes
      get edit_dossier_cnav_url(dossier_cnav)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DossierCnav" do
        expect {
          post dossier_cnavs_url, params: { dossier_cnav: valid_attributes }
        }.to change(DossierCnav, :count).by(1)
      end

      it "redirects to the created dossier_cnav" do
        post dossier_cnavs_url, params: { dossier_cnav: valid_attributes }
        expect(response).to redirect_to(dossier_cnav_url(DossierCnav.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DossierCnav" do
        expect {
          post dossier_cnavs_url, params: { dossier_cnav: invalid_attributes }
        }.to change(DossierCnav, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dossier_cnavs_url, params: { dossier_cnav: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dossier_cnav" do
        dossier_cnav = DossierCnav.create! valid_attributes
        patch dossier_cnav_url(dossier_cnav), params: { dossier_cnav: new_attributes }
        dossier_cnav.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dossier_cnav" do
        dossier_cnav = DossierCnav.create! valid_attributes
        patch dossier_cnav_url(dossier_cnav), params: { dossier_cnav: new_attributes }
        dossier_cnav.reload
        expect(response).to redirect_to(dossier_cnav_url(dossier_cnav))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dossier_cnav = DossierCnav.create! valid_attributes
        patch dossier_cnav_url(dossier_cnav), params: { dossier_cnav: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dossier_cnav" do
      dossier_cnav = DossierCnav.create! valid_attributes
      expect {
        delete dossier_cnav_url(dossier_cnav)
      }.to change(DossierCnav, :count).by(-1)
    end

    it "redirects to the dossier_cnavs list" do
      dossier_cnav = DossierCnav.create! valid_attributes
      delete dossier_cnav_url(dossier_cnav)
      expect(response).to redirect_to(dossier_cnavs_url)
    end
  end
end
