 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reversion_veuves", type: :request do
  # ReversionVeuve. As you add validations to ReversionVeuve, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReversionVeuve.create! valid_attributes
      get reversion_veuves_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      reversion_veuve = ReversionVeuve.create! valid_attributes
      get reversion_veuve_url(reversion_veuve)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_reversion_veuve_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      reversion_veuve = ReversionVeuve.create! valid_attributes
      get edit_reversion_veuve_url(reversion_veuve)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReversionVeuve" do
        expect {
          post reversion_veuves_url, params: { reversion_veuve: valid_attributes }
        }.to change(ReversionVeuve, :count).by(1)
      end

      it "redirects to the created reversion_veuve" do
        post reversion_veuves_url, params: { reversion_veuve: valid_attributes }
        expect(response).to redirect_to(reversion_veuve_url(ReversionVeuve.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReversionVeuve" do
        expect {
          post reversion_veuves_url, params: { reversion_veuve: invalid_attributes }
        }.to change(ReversionVeuve, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post reversion_veuves_url, params: { reversion_veuve: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reversion_veuve" do
        reversion_veuve = ReversionVeuve.create! valid_attributes
        patch reversion_veuve_url(reversion_veuve), params: { reversion_veuve: new_attributes }
        reversion_veuve.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the reversion_veuve" do
        reversion_veuve = ReversionVeuve.create! valid_attributes
        patch reversion_veuve_url(reversion_veuve), params: { reversion_veuve: new_attributes }
        reversion_veuve.reload
        expect(response).to redirect_to(reversion_veuve_url(reversion_veuve))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        reversion_veuve = ReversionVeuve.create! valid_attributes
        patch reversion_veuve_url(reversion_veuve), params: { reversion_veuve: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested reversion_veuve" do
      reversion_veuve = ReversionVeuve.create! valid_attributes
      expect {
        delete reversion_veuve_url(reversion_veuve)
      }.to change(ReversionVeuve, :count).by(-1)
    end

    it "redirects to the reversion_veuves list" do
      reversion_veuve = ReversionVeuve.create! valid_attributes
      delete reversion_veuve_url(reversion_veuve)
      expect(response).to redirect_to(reversion_veuves_url)
    end
  end
end
