 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/compta_nature_prestations", type: :request do
  # Admin::ComptaNaturePrestation. As you add validations to Admin::ComptaNaturePrestation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Admin::ComptaNaturePrestation.create! valid_attributes
      get admin_compta_nature_prestations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      compta_nature_prestation = Admin::ComptaNaturePrestation.create! valid_attributes
      get admin_compta_nature_prestation_url(admin_compta_nature_prestation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_compta_nature_prestation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      compta_nature_prestation = Admin::ComptaNaturePrestation.create! valid_attributes
      get edit_admin_compta_nature_prestation_url(admin_compta_nature_prestation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Admin::ComptaNaturePrestation" do
        expect {
          post admin_compta_nature_prestations_url, params: { admin_compta_nature_prestation: valid_attributes }
        }.to change(Admin::ComptaNaturePrestation, :count).by(1)
      end

      it "redirects to the created admin_compta_nature_prestation" do
        post admin_compta_nature_prestations_url, params: { admin_compta_nature_prestation: valid_attributes }
        expect(response).to redirect_to(admin_compta_nature_prestation_url(@admin_compta_nature_prestation))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Admin::ComptaNaturePrestation" do
        expect {
          post admin_compta_nature_prestations_url, params: { admin_compta_nature_prestation: invalid_attributes }
        }.to change(Admin::ComptaNaturePrestation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_compta_nature_prestations_url, params: { admin_compta_nature_prestation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_compta_nature_prestation" do
        compta_nature_prestation = Admin::ComptaNaturePrestation.create! valid_attributes
        patch admin_compta_nature_prestation_url(admin_compta_nature_prestation), params: { admin_compta_nature_prestation: new_attributes }
        compta_nature_prestation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_compta_nature_prestation" do
        compta_nature_prestation = Admin::ComptaNaturePrestation.create! valid_attributes
        patch admin_compta_nature_prestation_url(admin_compta_nature_prestation), params: { admin_compta_nature_prestation: new_attributes }
        compta_nature_prestation.reload
        expect(response).to redirect_to(admin_compta_nature_prestation_url(compta_nature_prestation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        compta_nature_prestation = Admin::ComptaNaturePrestation.create! valid_attributes
        patch admin_compta_nature_prestation_url(admin_compta_nature_prestation), params: { admin_compta_nature_prestation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_compta_nature_prestation" do
      compta_nature_prestation = Admin::ComptaNaturePrestation.create! valid_attributes
      expect {
        delete admin_compta_nature_prestation_url(admin_compta_nature_prestation)
      }.to change(Admin::ComptaNaturePrestation, :count).by(-1)
    end

    it "redirects to the admin_compta_nature_prestations list" do
      compta_nature_prestation = Admin::ComptaNaturePrestation.create! valid_attributes
      delete admin_compta_nature_prestation_url(admin_compta_nature_prestation)
      expect(response).to redirect_to(admin_compta_nature_prestations_url)
    end
  end
end
