 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/demande_carte_allocataires", type: :request do
  # Admin::DemandeCarteAllocataire. As you add validations to Admin::DemandeCarteAllocataire, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Admin::DemandeCarteAllocataire.create! valid_attributes
      get admin_demande_carte_allocataires_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      demande_carte_allocataire = Admin::DemandeCarteAllocataire.create! valid_attributes
      get admin_demande_carte_allocataire_url(admin_demande_carte_allocataire)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_demande_carte_allocataire_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      demande_carte_allocataire = Admin::DemandeCarteAllocataire.create! valid_attributes
      get edit_admin_demande_carte_allocataire_url(admin_demande_carte_allocataire)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Admin::DemandeCarteAllocataire" do
        expect {
          post admin_demande_carte_allocataires_url, params: { admin_demande_carte_allocataire: valid_attributes }
        }.to change(Admin::DemandeCarteAllocataire, :count).by(1)
      end

      it "redirects to the created admin_demande_carte_allocataire" do
        post admin_demande_carte_allocataires_url, params: { admin_demande_carte_allocataire: valid_attributes }
        expect(response).to redirect_to(admin_demande_carte_allocataire_url(@admin_demande_carte_allocataire))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Admin::DemandeCarteAllocataire" do
        expect {
          post admin_demande_carte_allocataires_url, params: { admin_demande_carte_allocataire: invalid_attributes }
        }.to change(Admin::DemandeCarteAllocataire, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_demande_carte_allocataires_url, params: { admin_demande_carte_allocataire: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_demande_carte_allocataire" do
        demande_carte_allocataire = Admin::DemandeCarteAllocataire.create! valid_attributes
        patch admin_demande_carte_allocataire_url(admin_demande_carte_allocataire), params: { admin_demande_carte_allocataire: new_attributes }
        demande_carte_allocataire.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_demande_carte_allocataire" do
        demande_carte_allocataire = Admin::DemandeCarteAllocataire.create! valid_attributes
        patch admin_demande_carte_allocataire_url(admin_demande_carte_allocataire), params: { admin_demande_carte_allocataire: new_attributes }
        demande_carte_allocataire.reload
        expect(response).to redirect_to(admin_demande_carte_allocataire_url(demande_carte_allocataire))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        demande_carte_allocataire = Admin::DemandeCarteAllocataire.create! valid_attributes
        patch admin_demande_carte_allocataire_url(admin_demande_carte_allocataire), params: { admin_demande_carte_allocataire: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_demande_carte_allocataire" do
      demande_carte_allocataire = Admin::DemandeCarteAllocataire.create! valid_attributes
      expect {
        delete admin_demande_carte_allocataire_url(admin_demande_carte_allocataire)
      }.to change(Admin::DemandeCarteAllocataire, :count).by(-1)
    end

    it "redirects to the admin_demande_carte_allocataires list" do
      demande_carte_allocataire = Admin::DemandeCarteAllocataire.create! valid_attributes
      delete admin_demande_carte_allocataire_url(admin_demande_carte_allocataire)
      expect(response).to redirect_to(admin_demande_carte_allocataires_url)
    end
  end
end
