 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/rentes", type: :request do
  # Admin::Rente. As you add validations to Admin::Rente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Admin::Rente.create! valid_attributes
      get admin_rentes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rente = Admin::Rente.create! valid_attributes
      get admin_rente_url(admin_rente)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_rente_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      rente = Admin::Rente.create! valid_attributes
      get edit_admin_rente_url(admin_rente)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Admin::Rente" do
        expect {
          post admin_rentes_url, params: { admin_rente: valid_attributes }
        }.to change(Admin::Rente, :count).by(1)
      end

      it "redirects to the created admin_rente" do
        post admin_rentes_url, params: { admin_rente: valid_attributes }
        expect(response).to redirect_to(admin_rente_url(@admin_rente))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Admin::Rente" do
        expect {
          post admin_rentes_url, params: { admin_rente: invalid_attributes }
        }.to change(Admin::Rente, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_rentes_url, params: { admin_rente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_rente" do
        rente = Admin::Rente.create! valid_attributes
        patch admin_rente_url(admin_rente), params: { admin_rente: new_attributes }
        rente.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_rente" do
        rente = Admin::Rente.create! valid_attributes
        patch admin_rente_url(admin_rente), params: { admin_rente: new_attributes }
        rente.reload
        expect(response).to redirect_to(admin_rente_url(rente))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rente = Admin::Rente.create! valid_attributes
        patch admin_rente_url(admin_rente), params: { admin_rente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_rente" do
      rente = Admin::Rente.create! valid_attributes
      expect {
        delete admin_rente_url(admin_rente)
      }.to change(Admin::Rente, :count).by(-1)
    end

    it "redirects to the admin_rentes list" do
      rente = Admin::Rente.create! valid_attributes
      delete admin_rente_url(admin_rente)
      expect(response).to redirect_to(admin_rentes_url)
    end
  end
end
