 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/reversion_veuve_salaries", type: :request do
  # Admin::ReversionVeuveSalarie. As you add validations to Admin::ReversionVeuveSalarie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Admin::ReversionVeuveSalarie.create! valid_attributes
      get admin_reversion_veuve_salaries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      reversion_veuve_salarie = Admin::ReversionVeuveSalarie.create! valid_attributes
      get admin_reversion_veuve_salary_url(admin_reversion_veuve_salary)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_reversion_veuve_salary_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      reversion_veuve_salarie = Admin::ReversionVeuveSalarie.create! valid_attributes
      get edit_admin_reversion_veuve_salary_url(admin_reversion_veuve_salary)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Admin::ReversionVeuveSalarie" do
        expect {
          post admin_reversion_veuve_salaries_url, params: { admin_reversion_veuve_salarie: valid_attributes }
        }.to change(Admin::ReversionVeuveSalarie, :count).by(1)
      end

      it "redirects to the created admin_reversion_veuve_salarie" do
        post admin_reversion_veuve_salaries_url, params: { admin_reversion_veuve_salarie: valid_attributes }
        expect(response).to redirect_to(admin_reversion_veuve_salary_url(@admin_reversion_veuve_salary))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Admin::ReversionVeuveSalarie" do
        expect {
          post admin_reversion_veuve_salaries_url, params: { admin_reversion_veuve_salarie: invalid_attributes }
        }.to change(Admin::ReversionVeuveSalarie, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_reversion_veuve_salaries_url, params: { admin_reversion_veuve_salarie: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_reversion_veuve_salarie" do
        reversion_veuve_salarie = Admin::ReversionVeuveSalarie.create! valid_attributes
        patch admin_reversion_veuve_salary_url(admin_reversion_veuve_salary), params: { admin_reversion_veuve_salary: new_attributes }
        reversion_veuve_salarie.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_reversion_veuve_salarie" do
        reversion_veuve_salarie = Admin::ReversionVeuveSalarie.create! valid_attributes
        patch admin_reversion_veuve_salary_url(admin_reversion_veuve_salary), params: { admin_reversion_veuve_salary: new_attributes }
        reversion_veuve_salarie.reload
        expect(response).to redirect_to(admin_reversion_veuve_salary_url(reversion_veuve_salarie))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        reversion_veuve_salarie = Admin::ReversionVeuveSalarie.create! valid_attributes
        patch admin_reversion_veuve_salary_url(admin_reversion_veuve_salary), params: { admin_reversion_veuve_salary: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_reversion_veuve_salarie" do
      reversion_veuve_salarie = Admin::ReversionVeuveSalarie.create! valid_attributes
      expect {
        delete admin_reversion_veuve_salary_url(admin_reversion_veuve_salary)
      }.to change(Admin::ReversionVeuveSalarie, :count).by(-1)
    end

    it "redirects to the admin_reversion_veuve_salaries list" do
      reversion_veuve_salarie = Admin::ReversionVeuveSalarie.create! valid_attributes
      delete admin_reversion_veuve_salary_url(admin_reversion_veuve_salary)
      expect(response).to redirect_to(admin_reversion_veuve_salaries_url)
    end
  end
end
