 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/salaire_annuels", type: :request do
  # Admin::SalaireAnnuel. As you add validations to Admin::SalaireAnnuel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Admin::SalaireAnnuel.create! valid_attributes
      get admin_salaire_annuels_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      salaire_annuel = Admin::SalaireAnnuel.create! valid_attributes
      get admin_salaire_annuel_url(admin_salaire_annuel)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_salaire_annuel_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      salaire_annuel = Admin::SalaireAnnuel.create! valid_attributes
      get edit_admin_salaire_annuel_url(admin_salaire_annuel)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Admin::SalaireAnnuel" do
        expect {
          post admin_salaire_annuels_url, params: { admin_salaire_annuel: valid_attributes }
        }.to change(Admin::SalaireAnnuel, :count).by(1)
      end

      it "redirects to the created admin_salaire_annuel" do
        post admin_salaire_annuels_url, params: { admin_salaire_annuel: valid_attributes }
        expect(response).to redirect_to(admin_salaire_annuel_url(@admin_salaire_annuel))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Admin::SalaireAnnuel" do
        expect {
          post admin_salaire_annuels_url, params: { admin_salaire_annuel: invalid_attributes }
        }.to change(Admin::SalaireAnnuel, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_salaire_annuels_url, params: { admin_salaire_annuel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_salaire_annuel" do
        salaire_annuel = Admin::SalaireAnnuel.create! valid_attributes
        patch admin_salaire_annuel_url(admin_salaire_annuel), params: { admin_salaire_annuel: new_attributes }
        salaire_annuel.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_salaire_annuel" do
        salaire_annuel = Admin::SalaireAnnuel.create! valid_attributes
        patch admin_salaire_annuel_url(admin_salaire_annuel), params: { admin_salaire_annuel: new_attributes }
        salaire_annuel.reload
        expect(response).to redirect_to(admin_salaire_annuel_url(salaire_annuel))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        salaire_annuel = Admin::SalaireAnnuel.create! valid_attributes
        patch admin_salaire_annuel_url(admin_salaire_annuel), params: { admin_salaire_annuel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_salaire_annuel" do
      salaire_annuel = Admin::SalaireAnnuel.create! valid_attributes
      expect {
        delete admin_salaire_annuel_url(admin_salaire_annuel)
      }.to change(Admin::SalaireAnnuel, :count).by(-1)
    end

    it "redirects to the admin_salaire_annuels list" do
      salaire_annuel = Admin::SalaireAnnuel.create! valid_attributes
      delete admin_salaire_annuel_url(admin_salaire_annuel)
      expect(response).to redirect_to(admin_salaire_annuels_url)
    end
  end
end
