 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/villes", type: :request do
  # Admin::Ville. As you add validations to Admin::Ville, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Admin::Ville.create! valid_attributes
      get admin_villes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ville = Admin::Ville.create! valid_attributes
      get admin_ville_url(admin_ville)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_ville_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ville = Admin::Ville.create! valid_attributes
      get edit_admin_ville_url(admin_ville)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Admin::Ville" do
        expect {
          post admin_villes_url, params: { admin_ville: valid_attributes }
        }.to change(Admin::Ville, :count).by(1)
      end

      it "redirects to the created admin_ville" do
        post admin_villes_url, params: { admin_ville: valid_attributes }
        expect(response).to redirect_to(admin_ville_url(@admin_ville))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Admin::Ville" do
        expect {
          post admin_villes_url, params: { admin_ville: invalid_attributes }
        }.to change(Admin::Ville, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_villes_url, params: { admin_ville: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_ville" do
        ville = Admin::Ville.create! valid_attributes
        patch admin_ville_url(admin_ville), params: { admin_ville: new_attributes }
        ville.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_ville" do
        ville = Admin::Ville.create! valid_attributes
        patch admin_ville_url(admin_ville), params: { admin_ville: new_attributes }
        ville.reload
        expect(response).to redirect_to(admin_ville_url(ville))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ville = Admin::Ville.create! valid_attributes
        patch admin_ville_url(admin_ville), params: { admin_ville: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_ville" do
      ville = Admin::Ville.create! valid_attributes
      expect {
        delete admin_ville_url(admin_ville)
      }.to change(Admin::Ville, :count).by(-1)
    end

    it "redirects to the admin_villes list" do
      ville = Admin::Ville.create! valid_attributes
      delete admin_ville_url(admin_ville)
      expect(response).to redirect_to(admin_villes_url)
    end
  end
end
