class Psrm::ComptaTransaction < Psrm::DbBase
  self.table_name = 'cisadm.XXIPRES_CSS_OP_ENT'

  attribute :legal_entity_id, :integer
  attribute :entity_id, :integer
  attribute :ledger_id, :integer
  attribute :created_by, :integer
  attribute :montant_op, :integer
  attribute :created_by, :integer

=begin
  LEGAL_ENTITY_ID
  ENTITY_ID
  CODE_TYPE_EVENEMENT
  DATE_EVENEMENT
  SECURITY_ID_INT_1
  LEDGER_ID
  ID_ALLOCATAIRE
  NOM_ALLOCATAIRE
  PNOM_ALLOCATAIRE
  ADRESSE_ALLOCATAIRE
  ADRESSE_RUE
  ADRESE_VILLE
  PAYS
  REGION
  MONTANT_OP
  MODE_DE_PAIEMENT
  CODE_BANQUE
  CODE_AGENCE
  NUMERO_COMPTE_ALLOC
  ZONE_DE_PAIEMENT
  CODE_AGENCE_PAIEMENT
  CODE_CAISSE_PAIEMENT
  NUMERO_ORDRE_PAIEMENT
  DESC_ORD_PAIEMENT
  NIN
  NUM_TEL
  EMAIL
  CATEG_ALLOCATAIRE
  NUM_ECHEANCE
  CODE_STATUT_TRANSACTION
  CODE_PROCESSUS_TRANSACTION
  BRANCHE_LIQ
  ATTRIBUTE1
  ATTRIBUTE2
  ATTRIBUTE3
  ATTRIBUTE4
  ATTRIBUTE5
  ATTRIBUTE6
  ATTRIBUTE7
  ATTRIBUTE8
  ATTRIBUTE9
  ATTRIBUTE10
  ATTRIBUTE11
  ATTRIBUTE12
  ATTRIBUTE13
  ATTRIBUTE14
  ATTRIBUTE15
  CREATION_DATE
  CREATED_BY
  LAST_UPDATE_DATE
  LAST_UPDATED_BY
  LAST_UPDATE_LOGIN
=end
end